/** @format */

import { StyleSheet } from "react-native";
// import { color } from "react-native-reanimated";

export const dashboard = StyleSheet.create({
	root: { padding: 10, minHeight: 300 },
	title: { textAlign: "center", fontSize: 30 },
	codeFieldRoot: { marginTop: 20 },
	text: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 16,
	},
	mainContainer: {
		backgroundColor: "#ffffff",
	},
	mainContainerNoti: {
		backgroundColor: "#ffffff",
		height: "100%",
	},
	container: {
		marginLeft: 20,
		backgroundColor: "#ffffff",
		height: "100%",
	},
	containerremodel: {
		marginRight: 20,
		backgroundColor: "#ffffff",
		// height: "100%",
	},
	containersumaary: {
		// marginHorizontal: 20,
		backgroundColor: "#ffffff",
		height: "100%",
	},
	// containersumaaryorder: {

	// },
	containercart: {
		// marginBottom: "50%",
		backgroundColor: "#E7E3F3",
		height: "100%",
	},
	containercartnewadress: {
		// margin: 20,
		backgroundColor: "white",
		borderRadius: 20,
		padding: 35,

		shadowOpacity: 6.25,
		shadowRadius: 4,
		elevation: 5,
		backgroundColor: "#E7E3F3",
		height: "100%",
	},
	containerproduct: {
		marginHorizontal: 10,
		backgroundColor: "#ffffff",
		height: "100%",
	},
	containerSearch: {
		// marginHorizontal: 20,
		backgroundColor: "#ffffff",
		height: "100%",
	},
	group: {
		display: "//grid//",
		flexDirection: "row",
		// marginHorizontal: 20,
	},
	groups: {
		display: "//grid//",
		flexDirection: "row",
		marginHorizontal: 20,
	},
	dropdown: {
		width: "10%",
	},
	groupcarttwo: {
		width: 400,
		flexDirection: "row",
		marginTop: 10,
	},
	groupcartcard: {
		backgroundColor: "#ffffff",
		display: "//grid//",
		flexDirection: "row",
		borderRadius: 10,
	},
	groupcartcardmain: {
		// height: "35%",
		backgroundColor: "#ffffff",
		borderRadius: 10,
	},
	groupcartcardtextgroup: {
		marginHorizontal: 15,
		marginVertical: 15,
		textDecoration: "underline",
	},
	groupcartcardtextgrouptwo: {
		display: "//grid//",
		flexDirection: "row",
		// marginVertical: 15,
	},
	line: {
		borderTop: 1,

		marginTop: 10,
		width: 350,
		marginHorizontal: 20,
		borderWidth: 1,
		borderColor: "#E7E3F3",
	},

	groupcartcardtext: {
		fontFamily: "PoppinsSemiBold",
		color: "#171520",
		fontSize: 16,
	},
	groupcartcardtexttwo: {
		fontFamily: "Poppins",
		color: "#626262",
		fontSize: 14,
	},
	grouplove: {
		display: "//grid//",
		flexDirection: "row",
		marginVertical: 10,
	},
	love: {
		marginLeft: 50,
	},
	groupheader: {
		display: "//grid//",
		flexDirection: "row",
		justifyContent: "space-between",
	},
	groupsmall: {
		marginHorizontal: 7,
		// width: "23%",
		// display: "flex",

		justifyContent: "space-between",
		marginVertical: 20,
	},
	newarival: {
		textAlign: "center",
		marginHorizontal: 7,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: 13,
	},
	newarivalsearch: {
		textAlign: "center",
		marginHorizontal: 20,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: 13,
		marginTop: 10,
	},
	groupImage: {
		borderRadius: "20%",
		marginRight: 10,
		marginBottom: 20,
		marginTop: -20,
	},
	groupImagesearch: {
		borderRadius: "20%",
		marginRight: 10,
		// marginBottom: 20,
		// marginTop: -20,
	},
	grouptwo: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: -10,
	},
	groupthree: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: 10,
	},
	textSmall: {
		textAlign: "center",
		// marginHorizontal: 7,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: 10,
	},
	textSmall2: {
		// textAlign: "center",
		// marginRight: 7,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: 12,
		color: "#0468BF",
	},
	groupview: {
		display: "//grid//",
		flexDirection: "row",
	},
	groupviewsearch: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: 10,
	},
	chevorn: {
		marginTop: -7,
		marginRight: 15,
	},
	colun: {
		flexDirection: "row",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: "90%",
	},
	cardsearch: {
		padding: 10,
		flexDirection: "row",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		width: "70%",
		maxHeight: 60,
		overflowY: "scroll",
	},

	inputcontainer: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 20,
		lineHeight: "26",
		// color: "#000000",
	},

	input: {
		// height: 40,
		color: "#000000",
		width: "85%",
		// borderWidth: 1,
		padding: 10,
		backgroundColor: "#F1F1F1",
		borderRadius: 5,
	},
	seacrchGroup: {
		marginHorizontal: 20,
	},
	groupcardcart: {
		marginHorizontal: 20,
		marginBottom: 20,
	},
	groupcardcartbelow: {
		marginHorizontal: 20,
		marginBottom: 20,
		display: "//grid//",
		flexDirection: "row",
		backgroundColor: "#FFFFFF",
		padding: 15,
		justifyContent: "space-between",
		borderRadius: 10,
	},
	groupcardcartbelowmore: {
		marginHorizontal: 20,
		marginBottom: 20,
		display: "//grid//",
		flexDirection: "row",
		backgroundColor: "#FFFFFF",
		padding: 15,
		justifyContent: "space-between",
		borderRadius: 10,
	},
	groupcardcartbelowtwo: {
		flexDirection: "row",
		justifyContent: "space-between",
		marginHorizontal: 20,
		marginBottom: 90,
		display: "inline//grid//",
		backgroundColor: "#FFFFFF",
		padding: 15,
		borderRadius: 10,
		gap: 10,
	},
	groupcardcartbelowtwo2: {
		flexDirection: "row",
		justifyContent: "space-between",
		// marginHorizontal: 20,
		marginBottom: 90,
		display: "inline//grid//",
		backgroundColor: "#FFFFFF",
		padding: 15,
		borderRadius: 10,
		gap: 10,
	},

	back: {
		marginTop: 7,
		marginRight: 10,
	},
	nullsearch: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 20,
		color: "#0468BF",
		marginTop: 2,
	},
	nullsearchtwo: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 20,
		color: "#0468BF",
		marginTop: 5,
		marginBottom: 10,
		// marginLeft: 20,
	},
	nullGroup: {
		marginHorizontal: 20,
	},
	nullimage: {
		marginVertical: 50,
		display: "flex",
		alignItems: "center",
	},
	nulltext: {
		textAlign: "center",
		marginVertical: 20,
		fontFamily: "PoppinsBold",
		fontStyle: "Medium",
		fontSize: "25",
	},
	nulltexttwo: {
		marginVertical: 20,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: "22",
	},
	nulltextsmall: {
		textAlign: "center",
		marginVertical: 20,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: "13",
	},
	oldprice: {
		textDecorationLine: "line-through",
		fontFamily: "PoppinsSemiBold",
		fontSize: 15,
		color: "#605979",
		marginLeft: 10,
		marginTop: 10,
	},
	oldprice2: {
		textDecorationLine: "line-through",
		fontFamily: "PoppinsSemiBold",
		fontSize: 13,
		color: "#605979",
		marginLeft: 10,
		marginTop: 10,
	},
	discount: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 15,
		marginLeft: 10,
		color: "#DB271A",
		marginTop: 10,
	},
	discount2: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 13,
		marginLeft: 10,
		color: "#DB271A",
		marginTop: 10,
	},
	newprice: {
		color: "#171520",
		textAlign: "center",
		marginTop: 5,
		fontFamily: "PoppinsBold",
		fontStyle: "Medium",
		fontSize: 22,
	},
	newprice2: {
		color: "#171520",
		textAlign: "center",
		marginTop: 5,
		fontFamily: "PoppinsBold",
		fontStyle: "Medium",
		fontSize: 18,
	},
	newpricetwo: {
		color: "#171520",
		textAlign: "center",
		marginTop: -55,
		fontFamily: "PoppinsBold",
		fontStyle: "Medium",
		fontSize: 22,
	},
	productname: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 18,

		color: "#171520",
		marginTop: 10,
	},
	productnamebelow: {
		fontFamily: "Poppins",
		fontSize: 12,

		color: "#605979",
		marginTop: 5,
	},
	productnamebelowtwo: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 14,

		color: "#605979",
		marginTop: 5,
	},
	productrating: {
		display: "//grid//",
		flexDirection: "row",
		backgroundColor: "#F4F4F4",
		marginRight: 20,
		width: "17%",
		height: 30,
		padding: 5,
		borderRadius: 5,
	},
	productratingsecond: {
		display: "//grid//",
		flexDirection: "row",
		// backgroundColor: "#F4F4F4",
		// marginRight: 10,
		width: "17%",
		height: 30,
		padding: 5,
		borderRadius: 5,
	},
	productinput: {
		marginHorizontal: 5,
	},
	productratingbellow: {
		// display: "//grid//",
		// flexDirection: "row",
		backgroundColor: "#E7E3F3",
		// marginRight: 0,
		// width: "34%",
		height: 60,
		padding: 10,
		alignItems: "center",
		borderRadius: 5,
	},
	averagerating: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 14,
		marginTop: -5,
		color: "#171520",
	},
	averageratingsecond: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 16,
		marginTop: 3,

		color: "#171520",
	},
	averateratetext: {
		marginRight: 5,
	},
	ratingReview: {
		fontFamily: "Poppins",
		fontSize: 12,

		color: "#605979",
		marginTop: 2,
	},
	terms: {
		fontFamily: "Poppins",
		fontSize: 11,

		color: "#0468BF",
		marginTop: 2,
	},
	rattingGroup: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: 10,
	},
	rattingGrouptwo: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: 10,
		marginBottom: 20,
	},
	rattingGroupbelow: {
		width: "24%",
		display: "//grid//",
		flexDirection: "row",
		padding: 10,
		borderWidth: 1,
		borderColor: "#E7E3F3",
		borderRadius: 5,
		marginRight: 10,
	},
	rategrouppercentage: {
		marginRight: 40,
	},
	averageratingoffer: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 12,
		marginTop: -5,
		color: "#171520",
	},
	productrattingtext: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 10,
		color: "#605979",
	},

	productinputtext: {
		marginHorizontal: 5,
		fontFamily: "PoppinsSemiBold",
		fontSize: 12,
	},
	deliverydetails: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 14,
		marginTop: 5,
		color: "#171520",
	},
	deliverydetails2: {
		fontFamily: "Poppins",
		fontSize: 14,
		marginTop: 5,
		color: "#605979",
	},
	button: {
		alignItems: "center",
		backgroundColor: "#0468BF",
		width: "80%",
		padding: 10,
		color: "#ffff",
		fontFamily: "Poppins",
		borderRadius: 10,
	},
	cartbutton: {
		color: "#0468BF",
		// width: "80%",
		// padding: 10,

		fontFamily: "Poppins",
		borderRadius: 10,
	},
	cartbuttongroup: {
		display: "//grid//",
		flexDirection: "row",
		justifyContent: "space-around",
	},
	cartgroup: {
		display: "//grid//",
		flexDirection: "row",
	},
	lovecart: {
		width: "14%",
		display: "//grid//",
		flexDirection: "row",
		padding: 15,
		alignItems: "center",
		backgroundColor: "#E7E3F3",
		borderRadius: 5,
		marginRight: 20,
	},
	groupcart: {
		display: "//grid//",
		flexDirection: "row",
		marginTop: 20,
	},
	groupdescription: {
		marginTop: 40,
		display: "//grid//",
		flexDirection: "row",
		justifyContent: "space-between",

		borderColor: "#F1F1F1",
		borderBottomWidth: 5,
		borderTopWidth: 5,
		// marginTop:20,
		padding: 10,
	},
	groupdescription2: {
		// marginTop: 40,
		display: "//grid//",
		flexDirection: "row",
		justifyContent: "space-between",

		borderColor: "#F1F1F1",

		padding: 10,
	},
	groupdescriptionbelow2: {
		borderColor: "#F1F1F1",
		borderBottomWidth: 5,
		borderTopWidth: 5,
		marginTop: 20,
		// padding:10
	},

	productdesc: {
		fontFamily: "PoppinsSemiBold",
		fontSize: "14",

		color: "#171520",
	},
	productdesctwo: {
		fontFamily: "PoppinsBold",
		fontSize: 16,
		marginTop: -60,
		color: "#171520",
	},
	nametext: {
		fontFamily: "PoppinsSemiBold",
		fontSize: "14",

		color: "#171520",
	},
	namemiddle: {
		fontFamily: "Poppins",
		fontSize: 12,

		color: "#605979",
	},
	comments: {
		marginTop: 10,
		fontFamily: "PoppinsBold",
		fontStyle: "Medium",
		fontSize: 16,
	},
	lorem: {
		fontFamily: "Poppins",
		fontSize: "14",
		color: "#605979",
	},
	///review///
	reviewbelow: {
		fontFamily: "PoppinsSemiBold",
		fontSize: 16,
		color: "#605979",
	},
	reviewtext: {
		marginTop: 40,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		fontSize: "20",
	},
	reviewtexttwo: {
		marginTop: 40,
		fontFamily: "PoppinsSemiBold",
		fontStyle: "Medium",
		// fontSize: 20,
		color: "#171520",
	},
	reviewinput: {
		width: "100%",
		height: 130,
		marginTop: 12,
		backgroundColor: "#E7E3F3",
		color: "#605979",
		paddingTop: 20,
		paddingLeft: 20,
		fontFamily: "PoppinsSemibold",
		FontSize: 19,
		borderRadius: "10",
	},
	buttonreview: {
		marginTop: "75%",
		backgroundColor: "#0468BF",
		width: "100%",
		padding: 10,
		color: "#ffff",
		fontFamily: "Poppins",
		borderRadius: 10,
	},
	buttonreviewcart: {
		marginHorizontal: 20,
		marginTop: "10%",
		backgroundColor: "#0468BF",
		// width: "100%",
		padding: 5,
		color: "#ffff",
		fontFamily: "Poppins",
		borderRadius: 10,
	},

	buttonreviewcartcheck: {
		// marginHorizontal: 20,
		// marginTop: "10%",
		backgroundColor: "#0468BF",
		// width: "100%",
		padding: 5,
		color: "#ffff",
		fontFamily: "Poppins",
		borderRadius: 10,
	},
	///null cart///
	nullcartimage: {
		marginVertical: 60,
		display: "flex",
		alignItems: "center",
	},
	nullcartimagetwo: {
		width: "100%",

		display: "flex",
		alignItems: "center",
	},
	cartnull: {
		fontFamily: "PoppinsBold",
		textAlign: "center",
		fontSize: "30",
		color: "#171520",
	},
	cartnulltwo: {
		fontFamily: "PoppinsSemiBold",
		textAlign: "center",
		fontSize: "17",
		color: "#171520",
		marginTop: 30,
	},
	hr: {
		borderRight: 1,
		borderTop: 0,
		borderBottom: 0,
		marginTop: 10,
		height: 25,
		borderWidth: 1,
		borderColor: "#E7E3F3",
	},
	cuppontext: {
		fontFamily: "Poppins",
		// textAlign: "center",
		fontSize: "14",
		color: "#605979",
		padding: 5,
	},
	cuppontext2: {
		marginTop: 5,
		fontFamily: "PoppinsSemiBold",
		// textAlign: "center",
		fontSize: "14",
		color: "#171520",
		padding: 5,
	},

	totalbag: {
		marginTop: 80,
	},
	totalbagtext: {
		fontFamily: "Poppins",
		// textAlign: "center",
		fontSize: "14",
		color: "#626262",
		padding: 5,
	},
	totalbagtextbold: {
		fontFamily: "PoppinsBold",
		// textAlign: "center",
		fontSize: "17",
		color: "#171520",
		padding: 5,
	},
	totalbagbutton: {
		marginTop: 100,
		width: "100%",
		backgroundColor: "#0468BF",
		color: "#ffffff",
		padding: 15,
		// paddingH:30,
		fontFamily: "Poppins",
		borderRadius: 10,
	},
	placeorder: {
		color: "#ffffff",
	},
	///////order summary////
	ordersummaryadress: {
		backgroundColor: "#E7E3F3",
		display: "//grid//",
		flexDirection: "row",
		padding: 20,
		justifyContent: "space-between",
		borderRadius: 10,
		marginHorizontal: 20,
	},
	ordersummaryadresstwo: {
		// backgroundColor: "#E7E3F3",
		display: "//grid//",
		flexDirection: "row",
		padding: 20,
		// justifyContent:"space-between",
		borderRadius: 10,
	},
	ordersummaryadresssummary: {
		fontFamily: "Poppins",
		// textAlign: "center",
		fontSize: "15",
		color: "#605979",
		padding: 5,
	},
	ordersummaryadresname: {
		fontFamily: "PoppinsSemiBold",
		// textAlign: "center",
		fontSize: "15",
		color: "#171520",
		padding: 5,
	},
	ordersummaryadresname2: {
		fontFamily: "Poppins",
		// textAlign: "center",
		fontSize: "15",
		color: "#605979",
		padding: 5,
	},
	deliverydetailsadress: {
		fontFamily: "PoppinsSemiBold",
		// textAlign: "center",
		fontSize: "15",
		color: "#171520",
		paddingLeft: 10,
		// padding:2,
	},
	deliverydetailsadress2: {
		fontFamily: "Poppins",

		fontSize: "13",
		color: "#605979",
		paddingLeft: 10,
	},
	groupcarttwonew: {
		height: "10%",
		backgroundColor: "#ffffff",
		display: "//grid//",
		flexDirection: "row",
		marginBottom: 30,
	},
});
